# Generated by Django 3.2.18 on 2023-04-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_listproperty_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='listproperty',
            name='property_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
