# Generated by Django 3.2.18 on 2023-04-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_listproperty_property_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listproperty',
            name='balcony',
            field=models.CharField(choices=[('Available', 'Available'), ('Not-Available', 'Not-Available')], default='Not-Available', max_length=100),
        ),
        migrations.AddField(
            model_name='listproperty',
            name='furnished',
            field=models.CharField(choices=[('Furnished', 'Furnished'), ('Semi-Furnished', 'Semi-Furnished'), ('Non-Furnished', 'Non-Furnished')], default='Non-Furnished', max_length=100),
        ),
    ]
