# Generated by Django 3.2.18 on 2023-04-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20230422_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='listproperty',
            name='no_of_bathroom',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listproperty',
            name='no_of_bedroom',
            field=models.IntegerField(default=1, max_length=3),
        ),
        migrations.AddField(
            model_name='listproperty',
            name='no_of_hall',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listproperty',
            name='no_of_kitchen',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listproperty',
            name='parking',
            field=models.CharField(choices=[('Available', 'Available'), ('Not-Available', 'Not-Available')], default='Not-Available', max_length=100),
        ),
    ]
