# Generated by Django 3.2.18 on 2023-04-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20230423_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listproperty',
            name='no_of_bedroom',
            field=models.IntegerField(default=1),
        ),
    ]
