# Generated by Django 3.2.18 on 2023-04-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_listproperty_no_of_bedroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listproperty',
            name='property_image',
            field=models.ImageField(blank=True, default='ds2.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='noprofil.jpg', null=True, upload_to=''),
        ),
    ]
